project:
  type: website
  output-dir: docs

website:
  title: "VectorCore Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: proyectos.qmd
        text: Portafolio
    tools:
    - icon: github
    href : https://github.com/Juliansoto29

format:
  html:
    link-external-newwindow: true
    theme: cosmo
    css: styles.css
    toc: true



